DASH_APP:
  APP_TITLE: GP Converter
  HEAD_TITLE: fiako-gpconverter | GP Converter
  UPDATE_TITLE: Updating...
  DEBUG: False
  ALIAS: fiako-gpconverter

TEMPLATE:
  WATERMARK_SOURCE: 
  THEME: MORPH

VERSION: v0.2.0
GITHUB_LINK: https://github.com/fiakoenjiniring/gpconverter
GITHUB_REPO: fiakoenjiniring/gpconverter