DASH_APP:
  APP_TITLE: GP Summary Converter
  HEAD_TITLE: fiako-gpconv | GP Summary Converter
  UPDATE_TITLE: Updating...
  DEBUG: False
  ALIAS: fiako-gpconv

TEMPLATE:
  WATERMARK_SOURCE: 
  THEME: SKETCHY

VERSION: v0.1.0
GITHUB_LINK: https://github.com/fiakoenjiniring/gpconv
GITHUB_REPO: fiakoenjiniring/gpconv